import Head from 'next/head'
import Image from 'next/image'
import styles from '../styles/Home.module.css'
import { useDrag } from 'react-use-gesture'
import { useSpring, animated } from 'react-spring'

// Original template for the homepage
//
// export default function Home() {
//   return (
//     <div className={styles.container}>
//       <Head>
//         <title>Create Next App</title>
//         <meta name="description" content="Generated by create next app" />
//         <link rel="icon" href="/favicon.ico" />
//       </Head>

//       <main className={styles.main}>
//         <h1 className={styles.title}>
//           Welcome to <a href="https://nextjs.org">Next.js!</a>
//         </h1>

//         <p className={styles.description}>
//           Get started by editing{' '}
//           <code className={styles.code}>pages/index.tsx</code>
//         </p>

//         <div className={styles.grid}>
//           <a href="https://nextjs.org/docs" className={styles.card}>
//             <h2>Documentation &rarr;</h2>
//             <p>Find in-depth information about Next.js features and API.</p>
//           </a>

//           <a href="https://nextjs.org/learn" className={styles.card}>
//             <h2>Learn &rarr;</h2>
//             <p>Learn about Next.js in an interactive course with quizzes!</p>
//           </a>

//           <a
//             href="https://github.com/vercel/next.js/tree/canary/examples"
//             className={styles.card}
//           >
//             <h2>Examples &rarr;</h2>
//             <p>Discover and deploy boilerplate example Next.js projects.</p>
//           </a>

//           <a
//             href="https://vercel.com/new?utm_source=create-next-app&utm_medium=default-template&utm_campaign=create-next-app"
//             target="_blank"
//             rel="noopener noreferrer"
//             className={styles.card}
//           >
//             <h2>Deploy &rarr;</h2>
//             <p>
//               Instantly deploy your Next.js site to a public URL with Vercel.
//             </p>
//           </a>
//         </div>
//       </main>

//       <footer className={styles.footer}>
//         <a
//           href="https://vercel.com?utm_source=create-next-app&utm_medium=default-template&utm_campaign=create-next-app"
//           target="_blank"
//           rel="noopener noreferrer"
//         >
//           Powered by{' '}
//           <span className={styles.logo}>
//             <Image src="/vercel.svg" alt="Vercel Logo" width={72} height={16} />
//           </span>
//         </a>
//       </footer>
//     </div>
//   )
// }

export default function Home(){
  const snowPos = useSpring({x:0, y:0})
  const snowLogoPos = useDrag((params) => {
    snowPos.x.set(params.offset[0]);
    snowPos.y.set(params.offset[1]);
  });
  const forestPos = useSpring({x:0, y:0})
  const forestLogoPos = useDrag((params) => {
    forestPos.x.set(params.offset[0]);
    forestPos.y.set(params.offset[1]);
  });
  const  mountPos = useSpring({x:0, y:0})
  const mountLogoPos = useDrag((params) => {
    mountPos.x.set(params.offset[0]);
    mountPos.y.set(params.offset[1]);
  });
  return(
    <div className={styles.container}>
      <Head>
        <title>My Test Page</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <div className={styles.row}>
          <animated.div {...snowLogoPos()} style={{
            x: snowPos.x,
            y: snowPos.y
          }}>
            <Image src="/img_snow.jpg" alt="Snow" className={styles.image} width={100} height={100}></Image>
          </animated.div>
          <animated.div {...forestLogoPos()} style={{
            x: forestPos.x,
            y: forestPos.y
          }}>
            <Image src="/img_forest.jpg" alt="Forest" className={styles.image} width={100} height={100}></Image>
          </animated.div>
          <animated.div {...mountLogoPos()} style={{
            x: mountPos.x,
            y: mountPos.y
          }}>
            <Image src="/img_mountains.jpg" alt="Mountains" className={styles.image} width={100} height={100}></Image>
          </animated.div>
      </div>
    </div>
  )
}
